#AppBundle_homepage:
#    pattern:  /
#    defaults: { _controller: AppBundle:ReadersAdmin:index }
#
#AppBundle_about:
#    pattern:  /about
#    defaults: { _controller: AppBundle:ReadersAdmin:about }
#    requirements:
#        _method:  GET
#
#AppBundle_readers:
#    pattern:  /readers
#    defaults: { _controller: AppBundle:ReadersAdmin:readers }
#    requirements:
#        _method:  GET|POST
#
#AppBundle_books:
#    pattern:  /books
#    defaults: { _controller: AppBundle:BooksAdmin:books }
#    requirements:
#        _method:  GET|POST

#AppBundle_books_show:
#    pattern:  /{id}
#    defaults: { _controller: AppBundle:Books:show }
#    requirements:
#        _method:  GET
#        id: \d+
#
#AppBundle_readers_show:
#    pattern:  /{id}
#    defaults: { _controller: AppBundle:Books:show }
#    requirements:
#        _method:  GET
#        id: \d+